export const CATEGORY_CHECK = 'CATEGORY_CHECK';
export const CATEGORY_UNCHECK = 'CATEGORY_UNCHECK';
export  const CATEGORY_UNCHECK_ALL = 'CATEGORY_UNCHECK_ALL';
export const QUESTIONS_SELECTED = 'QUESTIONS_SELECTED';